### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by vsspt** [react-workspaces/create-react-app#18]
I'm having this error when executing yarn:app start:

`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined at validateString (internal/validators.js:118:11) at Object.join (path.js:1039:7) at noopServiceWorkerMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26) at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:317:13) at /var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:335:12) at next (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:275:10) at launchEditorMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7) at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:317:13) at /var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:335:12) at next (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/index.js:275:10) at handleWebpackInternalMiddleware (/var/www/html/react-workspaces-playground/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7) at Layer.handle [as handle_request] (/var/www/html/react-workspaces-playground/node_modules/express/lib/router/layer.js:95:5)
`

**Tools and versions:**
- Windows 10 Enterprise 
- Yarn: v1.19.0 (cannot use v1.22.0, due to this [error](https://github.com/yarnpkg/yarn/issues/7734)).
- Lerna: 3.20.2
- @react-workspaces/react-scripts: 3.3.0-alpha-08

According to [this](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re) stackoverflow topic, this error should be resolved by upgrading the react-scripts version to 3.4.0.

**Comment by zipzapp** [comment]
version 3.4.0 needs to be merged into this fork

**Comment by keshikashviligio** [comment]
@F1LT3R Hi could you review this: https://github.com/react-workspaces/create-react-app/pull/19 pull request and merge?

**Comment by F1LT3R** [comment]
~~@keshikashviligio did you want to merge 3.4.0 into this fork as @zipzapp suggested?~~

Nm, I had read these in reverse order.
