### ISSUE TITLE
3.0.1-alpha-05 released

### ISSUE THREAD

**Issue by rek** [react-workspaces/create-react-app#2]
Hi there,

I'm using react-workspaces and it is pretty great, thanks!

I notice 3.0.1 is deployed on NPM (https://www.npmjs.com/package/@react-workspaces/react-scripts) but the changes are not pushed here. Would love it if you could push so we can see too and know if we need to upgrade.

Thanks,

**Comment by alistair-hmh** [comment]
Good call. Will try and get to this soon.

**Comment by F1LT3R** [comment]
Ok, @rek, I've have ....

- Updated `@react-worrkspaces/react-scripts` to `@3.0.1-alpha-07` on NPM (this takes care of create-react-app sever not closing gracefully.
- Pushed latest @react-workspaces/create-react-app here to keep things inline.
- Updated `@react-scripts/react-workspaces-playground` with the latest version.

FYI @sgadman ^^

**Comment by rek** [comment]
Awesome thanks heaps!
