### ISSUE TITLE
Issue with babel-jest version mismatch.

### ISSUE THREAD

**Issue by shambhusingh** [react-workspaces/create-react-app#4]
These is an issue whenever I do "yarn install" or "yarn" as it overrides the yarn.lock file and with this whenever I run "yarn start" into my libraries or apps it fails with the following errors:

```
The @react-workspaces/react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "24.7.1"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /ROOT/sample-app/node_modules/babel-jest (version: 24.8.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.
.
....
......
```

Is this issue because of base CRA and "@react-workspaces/react-scripts" using different version.? Not sure.

Don't want to use `SKIP_PREFLIGHT_CHECK=true` for all the modules.

Again tried with `--frozen-lockfile true` in `yarnrc` but this also does not solve it.

Any Idea, what I am doing wrong there.?

Deleting 'yarn.lock' before `yarn install`, things work fine, but I need to do it all the time whenever `yarn install` needed. 

Used versions: 
Node: v12.6.0,
Yarn: 1.17.3,
babel-eslint: v10.0.1

**Comment by shambhusingh** [comment]
Got it working by adding babel and jest dependent modules into `workspaces > nohoist`

```
 "workspaces": {
    "packages": [
      "packages/*
    ],
    "nohoist": [
      "**/babel**",
      "**/jest",
      ..........
      ............
      .............
    ]
  },
```

**Comment by MikeSuiter** [comment]
We have the nohoist but still get the problem at times. @shambhusingh has this solution still been working for you?
