### ISSUE TITLE
Security issue: Need to upgrade jest

### ISSUE THREAD

**Issue by Clebiez** [react-workspaces/create-react-app#8]
Hi,

High security issue have been reported to **handlebars** package used in the tree below : 

`@react-workspaces/react-scripts > jest-cli > @jest/core > @jest/reporters > istanbul-reports > handlebars`

[Link of the report](https://www.npmjs.com/advisories/1164)

Your jest is under the 24.7.1 version.
I think upgrade to the latest version (24.9.0) will solve this security issue.

**Comment by lhas2** [comment]
I totally agree! We need the `jest` with the latest versio `24.9.0`. This is generating some conflicts with other react apps in the same monorepo.

**Comment by wab** [comment]
up on this upgrade demand!

**Comment by F1LT3R** [comment]
Thanks for the heads up. Looking to upgrade this some time this week.

**Comment by F1LT3R** [comment]
This should be fixed soon in PR: https://github.com/react-workspaces/react-workspaces-playground/pull/21

<img width="782" alt="CleanShot 2019-12-26 at 23 54 10@2x" src="https://user-images.githubusercontent.com/1218446/71501896-0927b480-283b-11ea-94ba-172405d4e74d.png">
